"""dev20201020

Revision ID: 66a8d2894d6c
Revises: 198b0eebcf9
Create Date: 2020-10-20 15:50:28.224916

"""

# revision identifiers, used by Alembic.
revision = '66a8d2894d6c'
down_revision = '198b0eebcf9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'password_time')
    # ### end Alembic commands ###
