"""files db5

Revision ID: 7e60482e6dd3
Revises: ce7d189e51a8
Create Date: 2020-11-03 21:28:48.429815

"""

# revision identifiers, used by Alembic.
revision = '7e60482e6dd3'
down_revision = 'ce7d189e51a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('filesender', sa.String(length=64), nullable=True),
    sa.Column('filerecipient', sa.String(length=64), nullable=True),
    sa.Column('filediscription', sa.Text(), nullable=True),
    sa.Column('downloadcount', sa.Integer(), nullable=True),
    sa.Column('checkflag', sa.Integer(), nullable=True),
    sa.Column('checker', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Files_filename'), 'Files', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Files_filename'), table_name='Files')
    op.drop_table('Files')
    # ### end Alembic commands ###
