"""file upload2

Revision ID: 969477c8d95f
Revises: bbbd8b0a022d
Create Date: 2020-10-29 11:21:09.935937

"""

# revision identifiers, used by Alembic.
revision = '969477c8d95f'
down_revision = 'bbbd8b0a022d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('filesender', sa.String(length=64), nullable=True),
    sa.Column('filerecipient', sa.String(length=64), nullable=True),
    sa.Column('filediscription', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Files_filename'), 'Files', ['filename'], unique=True)
    op.drop_index('ix_Files_filename', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('filesender', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('filerecipient', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('filediscription', mysql.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Files_filename', 'files', ['filename'], unique=True)
    op.drop_index(op.f('ix_Files_filename'), table_name='Files')
    op.drop_table('Files')
    # ### end Alembic commands ###
