"""file upload3

Revision ID: a38f1bae390c
Revises: 969477c8d95f
Create Date: 2020-10-29 16:28:53.237473

"""

# revision identifiers, used by Alembic.
revision = 'a38f1bae390c'
down_revision = '969477c8d95f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('filesender', sa.String(length=64), nullable=True),
    sa.Column('filerecipient', sa.String(length=64), nullable=True),
    sa.Column('filediscription', sa.Text(), nullable=True),
    sa.Column('downloadcount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Files_filename'), 'Files', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Files_filename'), table_name='Files')
    op.drop_table('Files')
    # ### end Alembic commands ###
