"""files db7

Revision ID: c496d6534d49
Revises: 7655b988c964
Create Date: 2020-11-03 22:19:34.851676

"""

# revision identifiers, used by Alembic.
revision = 'c496d6534d49'
down_revision = '7655b988c964'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('filesender', sa.String(length=64), nullable=True),
    sa.Column('filerecipient', sa.String(length=64), nullable=True),
    sa.Column('filediscription', sa.Text(), nullable=True),
    sa.Column('downloadcount', sa.Integer(), nullable=True),
    sa.Column('checkflag', sa.Integer(), nullable=True),
    sa.Column('checker', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['filerecipient'], ['users.phone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Files_filename'), 'Files', ['filename'], unique=True)
    op.drop_index('ix_Files_filename', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('filesender', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('filerecipient', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('filediscription', mysql.TEXT(), nullable=True),
    sa.Column('downloadcount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('checkflag', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('checker', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['filerecipient'], ['users.phone'], name='files_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Files_filename', 'files', ['filename'], unique=True)
    op.drop_index(op.f('ix_Files_filename'), table_name='Files')
    op.drop_table('Files')
    # ### end Alembic commands ###
