"""files db4

Revision ID: e95b5ea29779
Revises: a38f1bae390c
Create Date: 2020-11-03 21:24:50.938236

"""

# revision identifiers, used by Alembic.
revision = 'e95b5ea29779'
down_revision = 'a38f1bae390c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('filesender', sa.String(length=64), nullable=True),
    sa.Column('filerecipient', sa.String(length=64), nullable=True),
    sa.Column('filediscription', sa.Text(), nullable=True),
    sa.Column('downloadcount', sa.Integer(), nullable=True),
    sa.Column('checkflag', sa.Integer(), nullable=True),
    sa.Column('checker', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Files_filename'), 'Files', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Files_filename'), table_name='Files')
    op.drop_table('Files')
    # ### end Alembic commands ###
